name: Deploy HTML Report

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install artillery globally
        run: |
          npm install -g artillery
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build . -t nest:latest

      - name: Run artillery test
        run: |
          - docker run nest:latest artillery run nest.yaml --output nest.json
          
      - name: Run artillery report
        run: |
          - docker run nest:latest artillery report nest.json --output index.html     
          
      - name: Publish HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: index
          path: ./
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

    
