name: Deploy HTML Report

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install artillery globally
        run: |
          npm install -g artillery
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build . -t nest:latest

      - name: Run tests with Artillery
        run: |
          docker run nest:latest sh -c "artillery run nest.yml --output /app/output.json && artillery report /app/output.json --output /app/index.html"

      - name: Copy HTML report from container
        run: |
          docker cp $(docker ps -lq):/app/index.html ./index.html
          docker cp $(docker ps -lq):/app/output.json ./output.json 

      - name: Publish HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: frsh-report
          path: index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./

    
